### ISSUE TITLE
geonode does not show maps (related to datapackage-importer cherry-picks i suppose

### ISSUE THREAD

**Issue by mwallschlaeger** [zalf-rdm/geonode-mapstore-client#1]
current installation on draven uses this geonode-mapstore-client. @mwallschlaeger did some cherry-picking on the thuenen mapstore-client to integrate the required changes for the `datapackage-importer`. I guess this somehow broke the map feature.

Ether 52N creates startes form a fresh `geonode-mapstore-client` fork to integrate the table view or they're using thisone and try to fix this version. IDK whats better

**Comment by specka** [comment]
Maybe done by 52N

**Comment by ridoo** [comment]
@mwallschlaeger Is this one related or even resolved by creating [the development repository](https://github.com/GeoNodeUserGroup-DE/geonode-dev-datapackage) for the datapackage feature?

**Comment by mwallschlaeger** [comment]
@ridoo yes i think this is going to fix the issue
